---
grails:
    profile: web
    codegen:
        defaultPackage: transaction_drill
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSources:
    dataSource:
        pooled: true
        jmxExport: true
        driverClassName: com.mysql.cj.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dbCreate: none
        url: jdbc:mysql://<HOST>/<Database>?zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
        username: <username_here>
        password: <pwd>
        properties:
            maxActive: 100
            maxIdle: 25
            minIdle: 5
            initialSize: 5
            maxWait: 120000 # increase maxWait to 120 seconds
            maxAge: 120000
            removeAbandoned: true
            removeAbandonedTimeout: 3600
            logAbandoned: true
            minEvictableIdleTimeMillis: 5000
            timeBetweenEvictionRunsMillis: 15000
            numTestsPerEvictionRun: 3
            testOnBorrow: true
            testWhileIdle: true
            testOnReturn: true
            validationQuery: "SELECT 1"
    rds:
        pooled: true
        jmxExport: true
        driverClassName: com.mysql.cj.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dbCreate: none
        url: jdbc:mysql://<HOST>/<Database>?zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
        username: <username_here>
        password: <pwd>
        properties:
            maxActive: 100
            maxIdle: 25
            minIdle: 5
            initialSize: 5
            maxWait: 120000 # increase maxWait to 120 seconds
            maxAge: 120000
            removeAbandoned: true
            removeAbandonedTimeout: 3600
            logAbandoned: true
            minEvictableIdleTimeMillis: 5000
            timeBetweenEvictionRunsMillis: 15000
            numTestsPerEvictionRun: 3
            testOnBorrow: true
            testWhileIdle: true
            testOnReturn: true
            validationQuery: "SELECT 1"
    maria:
        pooled: true
        jmxExport: true
        driverClassName: com.mysql.cj.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dbCreate: none
        url: jdbc:mysql://<HOST>/<Database>?zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
        username: <username_here>
        password: <pwd>
        properties:
            maxActive: 100
            maxIdle: 25
            minIdle: 5
            initialSize: 5
            maxWait: 120000 # increase maxWait to 120 seconds
            maxAge: 120000
            removeAbandoned: true
            removeAbandonedTimeout: 3600
            logAbandoned: true
            minEvictableIdleTimeMillis: 5000
            timeBetweenEvictionRunsMillis: 15000
            numTestsPerEvictionRun: 3
            testOnBorrow: true
            testWhileIdle: true
            testOnReturn: true
            validationQuery: "SELECT 1"
